### PR TITLE
Fix spacing

### PR DESCRIPTION
**Pull request by brennv**

### CODE REVIEW

**Comment by brennv** [comment]
Initial tests are [passing](https://travis-ci.org/linkedin/luminol/builds/269300703?utm_source=github_status&utm_medium=notification) for 2.7 

I'll start adding more files to this PR.

**Comment by brennv** [comment]
Passing for 2.7 https://travis-ci.org/linkedin/luminol/builds/269308780

Ready to merge, we can pretty up the tests later if we want.

**Comment by RiteshMaheshwari** [comment]
How about we focus on 2.7 only for now? Let's take up fixing for 3.6 separately. In that case, can you change the travis.yml to remove 3.6?

**Comment by brennv** [comment]
Sounds good, this PR is green now with 48fc2ad

https://travis-ci.org/linkedin/luminol/pull_requests

Merging this should change this red badge to green for master:

https://travis-ci.org/linkedin/luminol.svg?branch=master

**Pull request merged**
